#!/usr/bin/env bash
# update package lists and install Nginx

sudo apt-get update -y
sudo apt-get install nginx -y

# configure ngix to listen at port 80 and serve hello world
echo "server {
     listen 80;
     location / {
     	      	echo 'Hello World!';
		}
}" > /var/www/html/index.html

# restart nginx

service nginx restart