#!/usr/bin/env bash
# Script that configures Ngix server with a custom header

sudo apt-get update -y
sudo apt-get install nginx -y



sudo bash -c "cat > /etc/nginx/sites-available/default <<EOF
server {
       listen 80 default_server;
       listen [::]:80 default_server;
       server_name _;
       add_header X-Served-By \$hostname;
       root /var/www/html;
       index index.html index.htm;
       location / {
       		try_files \$uri \$uri/ =404;
       }
}

EOF"
sudo service start nginx
