#!/usr/bin/env bash
# Script that configures Ngix server with a custom header
var=$(hostname)
new_string="error_page 404 \/custome.html;\n location \/redirect_me {\n return 301 \$scheme;\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx start
